/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mike.utils.jsimplecalendar.demo;

import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import mike.utils.DateUtil;
import mike.utils.jsimplecalendar.exception.CalendarFormatException;

/**
 *
 * @author mike
 */
public class DemoJSimpleCalendar extends javax.swing.JFrame {

    /**
     * Creates new form DemoJSimpleCalendar
     */
    public DemoJSimpleCalendar() {
            initComponents();
            jCalendarComboField1.setToolTipText("jCalendarComboField");
            jCalendarHeaderField1.setToolTipText("jCalendarHeaderField");
            jCalendarHeader1.setToolTipText("jCalendarHeader");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jCalendarHeader1 = new mike.utils.jsimplecalendar.component.JCalendarHeader();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCalendarHeaderField1 = new mike.utils.jsimplecalendar.component.JCalendarHeaderField();
        jCalendarComboField1 = new mike.utils.jsimplecalendar.component.JCalendarComboField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setText("JCalendarPane");

        jButton1.setText("commit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jCalendarHeader1.addSelectionChangedListener(new mike.utils.jsimplecalendar.event.SelectionChangedListener() {
            public void onSelectionChanged(mike.utils.jsimplecalendar.event.SelectionChangedEvent evt) {
                jCalendarHeader1OnSelectionChanged(evt);
            }
        });
        jCalendarHeader1.addDateChangedListener(new mike.utils.jsimplecalendar.event.DateChangedListener() {
            public void nextMonthChanged(mike.utils.jsimplecalendar.event.DateChangedEvent evt) {
                jCalendarHeader1NextMonthChanged(evt);
            }
            public void prevMonthChanged(mike.utils.jsimplecalendar.event.DateChangedEvent evt) {
                jCalendarHeader1PrevMonthChanged(evt);
            }
            public void nextYearChanged(mike.utils.jsimplecalendar.event.DateChangedEvent evt) {
                jCalendarHeader1NextYearChanged(evt);
            }
            public void prevYearChanged(mike.utils.jsimplecalendar.event.DateChangedEvent evt) {
                jCalendarHeader1PrevYearChanged(evt);
            }
        });

        jLabel1.setText("Calendar Field");

        jLabel2.setText("Calendar");

        jLabel3.setText("Calendar Field (JComboBox)");

        jLabel4.setText("Event SelectionChange");

        jTextField2.setText("jTextField2");

        jButton2.setText("commit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("commit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextField3.setText("jTextField3");

        jTextField4.setText("jTextField4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jCalendarHeader1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCalendarComboField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCalendarHeaderField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCalendarHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCalendarHeaderField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCalendarComboField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton3)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jTextField1.setText(new DateUtil().formatoDiaMesAnio(jCalendarHeader1.getDateSelected()));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCalendarHeader1OnSelectionChanged(mike.utils.jsimplecalendar.event.SelectionChangedEvent evt) {//GEN-FIRST:event_jCalendarHeader1OnSelectionChanged
        jTextField2.setText(new DateUtil().formatoDiaMesAnio(jCalendarHeader1.getDateSelected()));
    }//GEN-LAST:event_jCalendarHeader1OnSelectionChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            if(jCalendarHeaderField1.isEmpty())
                JOptionPane.showMessageDialog(this, "esta vacio");
            jTextField3.setText(new DateUtil().formatoDiaMesAnio(jCalendarHeaderField1.getDate()));
        }
        catch (CalendarFormatException ex) {
            Logger.getLogger(DemoJSimpleCalendar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jCalendarHeader1NextMonthChanged(mike.utils.jsimplecalendar.event.DateChangedEvent evt) {//GEN-FIRST:event_jCalendarHeader1NextMonthChanged
        System.out.println("nm");
    }//GEN-LAST:event_jCalendarHeader1NextMonthChanged

    private void jCalendarHeader1NextYearChanged(mike.utils.jsimplecalendar.event.DateChangedEvent evt) {//GEN-FIRST:event_jCalendarHeader1NextYearChanged
        System.out.println("ny");
    }//GEN-LAST:event_jCalendarHeader1NextYearChanged

    private void jCalendarHeader1PrevMonthChanged(mike.utils.jsimplecalendar.event.DateChangedEvent evt) {//GEN-FIRST:event_jCalendarHeader1PrevMonthChanged
        System.out.println("pm");
    }//GEN-LAST:event_jCalendarHeader1PrevMonthChanged

    private void jCalendarHeader1PrevYearChanged(mike.utils.jsimplecalendar.event.DateChangedEvent evt) {//GEN-FIRST:event_jCalendarHeader1PrevYearChanged
        System.out.println("py");
    }//GEN-LAST:event_jCalendarHeader1PrevYearChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        DemoJSimpleCalendar a = new DemoJSimpleCalendar();
                a.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private mike.utils.jsimplecalendar.component.JCalendarComboField jCalendarComboField1;
    private mike.utils.jsimplecalendar.component.JCalendarHeader jCalendarHeader1;
    private mike.utils.jsimplecalendar.component.JCalendarHeaderField jCalendarHeaderField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables

}
